(function(){
  'use strict';
  if(!window.firebase||!firebase.apps.length)return;
  var db=firebase.database(),storage=firebase.storage(),fn=firebase.app().functions('asia-southeast1');
  var saveSession=fn.httpsCallable('polaroidSaveSession'),saveProduct=fn.httpsCallable('polaroidSaveProduct'),deleteProduct=fn.httpsCallable('polaroidDeleteProduct'),setStatus=fn.httpsCallable('polaroidSetMaidStatus'),updateTask=fn.httpsCallable('polaroidUpdateTask'),assignRound=fn.httpsCallable('polaroidAssignTaskRound');
  var scheduler=window.CafeSchedule,clockOffset=0,macroStaff='',macroDirty=false,dueMacroStaff='',dueMacroDirty=false;
  var specialTask=fn.httpsCallable('polaroidSpecialTask'),cancelOrder=fn.httpsCallable('polaroidCancelOrder'),markNotified=fn.httpsCallable('polaroidMarkNotified'),saveMacro=fn.httpsCallable('polaroidSaveMacro');
  function timeNow(){return Date.now()+clockOffset}
  function safeSlots(){try{return session?scheduler.slots(session):[]}catch(_){return[]}}
  function activeRound(t){try{return scheduler.effective(session,t,timeNow())}catch(_){return t.roundId||''}}
  var session=null,sessionId='',operation={},roster={},isManager=false,sessionRef=null,roundSeed=0,exampleSeed=0,editingProduct=null;
  function el(id){return document.getElementById(id)}
  function esc(v){var d=document.createElement('div');d.textContent=String(v==null?'':v);return d.innerHTML}
  function staffId(){try{return localStorage.getItem('lephemereCurrentStaffId')||''}catch(_){return''}}
  function staffName(id){return(roster[id]||{}).name||'未命名女僕'}
  function list(v){return Array.isArray(v)?v:Object.values(v||{})}
  function done(t){return scheduler.finished(t)}
  async function checkRole(user){if(!user)return;var values=await Promise.all([db.ref('lephemere/todayStaff/_access/ownerUid').once('value'),db.ref('lephemere/todayStaff/_access/users/'+user.uid+'/role').once('value')]),role=values[1].val()||'';isManager=String(user.email||'').toLowerCase()==='tanjicafe@gmail.com'||values[0].val()===user.uid||role==='manager'}
  function rounds(){return Object.entries((session&&session.rounds)||{}).sort(function(a,b){return Number(a[1].sortOrder||0)-Number(b[1].sortOrder||0)})}
  function products(){return Object.entries((session&&session.products)||{}).map(function(pair){return Object.assign({id:pair[0]},pair[1]||{})}).sort(function(a,b){return Number(a.sortOrder||0)-Number(b.sortOrder||0)})}
  function roundLabel(id){var r=session&&session.rounds&&session.rounds[id];return r?((r.label||'')+' '+(r.startTime||'')+(r.endTime?'–'+r.endTime:'')):'不需輪次'}
  function tasks(){return session?scheduler.allTasks(session):[]}
  window.LephemerePolaroidAccounting=function(date){var result={orderCount:0,total:0,taskCount:0,completed:0,deferred:0,commonRevenue:0,personalRevenue:0,unassignedRevenue:0,specialByStaff:{},staffNames:{}};if(!session||String(session.businessDate||'')!==String(date||''))return result;Object.values(session.orders||{}).forEach(function(order){if(!order||['paid','completed'].indexOf(order.status)===-1)return;result.orderCount++;result.total+=Number(order.total||0);Object.values(order.tasks||{}).forEach(function(task){if(!task)return;var price=Number(task.price||0),ids=list(task.revenueMaidIds).filter(Boolean);result.taskCount++;if(done(task))result.completed++;if(task.status==='deferred'||task.status==='no_show')result.deferred++;if(task.revenueMode==='shared'){result.commonRevenue+=price;return}if(task.revenueMode==='maid'&&ids.length>1)ids=ids.slice(0,1);if(!ids.length&&task.maidId)ids=[task.maidId];if(!ids.length){result.unassignedRevenue+=price;return}var share=price/ids.length;ids.forEach(function(id){result.specialByStaff[id]=(result.specialByStaff[id]||0)+share;result.staffNames[id]=staffName(id)});result.personalRevenue+=price})});return result};
  window.LephemerePolaroidCheckout=function(visitId){return scheduler.checkout(session,visitId)};
  function statusText(s){return{pending:'待拍',shooting:'拍攝中',completed:'拍攝完成',delivered:'已完成並交付',deferred:'暫時跳過（保留順位）',no_show:'暫時未到',cancelled:'已取消'}[s]||s}
  function ownsTask(t,id){return t.maidId===id||list(t.providerIds).indexOf(id)!==-1}
  function roundOptions(selected){return rounds().map(function(pair){return'<option value="'+esc(pair[0])+'" '+(pair[0]===selected?'selected':'')+'>'+esc(roundLabel(pair[0]))+'</option>'}).join('')}
  function notificationState(t){if(!t.lastNotifiedAt)return{label:'尚未通知',outdated:false};var id=activeRound(t),r=session&&session.rounds&&session.rounds[id]||{},outdated=id!==(t.lastNotifiedRoundId||'')||String(r.startTime||'')!==String(t.lastNotifiedStartTime||'')||String(r.endTime||'')!==String(t.lastNotifiedEndTime||''),time=new Date(t.lastNotifiedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});return{label:outdated?'先前已通知，但安排已更新｜請重新通知':('已通知 '+time+'｜'+(t.lastNotifiedByMaidName||staffName(t.lastNotifiedByMaidId))),outdated:outdated}}
  function currentSlot(){var time=timeNow();return safeSlots().find(function(r){return r.start<=time&&time<r.end})}
  function taskIsDue(t){var slot=currentSlot();return !!slot&&activeRound(t)===slot.id}
  function dueNotificationState(t){if(!t.lastDueNotifiedAt)return{label:'尚未發送到時提醒',outdated:false};var id=activeRound(t),outdated=id!==(t.lastDueNotifiedRoundId||''),time=new Date(t.lastDueNotifiedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit'});return{label:outdated?'先前提醒屬於其他時段｜請重新確認':('已於 '+time+' 發送到時提醒｜'+(t.lastDueNotifiedByMaidName||staffName(t.lastDueNotifiedByMaidId))),outdated:outdated}}
  function taskHtml(t){
    var id=activeRound(t),attrs=' data-order="'+esc(t.orderId)+'" data-task="'+esc(t.taskId)+'" data-maid="'+esc(t.maidId)+'"',actions='';
    function button(status,label,help){return '<button class="btn ghost small" data-photo-action="'+status+'"'+attrs+(help?' data-help="'+esc(help)+'" title="'+esc(help)+'" aria-label="'+esc(label+'：'+help)+'"':'')+'>'+label+'</button>'}
    if((isManager||ownsTask(t,staffId()))&&!done(t)){
      if(t.taskType==='shoot'){
        if(t.status==='shooting')actions+=button('completed','拍攝完成');
        else{actions+=button('shooting','開始拍攝','安排時段外也能開始，系統會先顯示確認提醒並保留操作紀錄。');actions+=button('deferred','暫時跳過','女僕目前無法拍攝；保留原下單順位，之後可繼續處理。')+button('no_show','暫時未到','客人目前不在場；不會卡住後續工作，回來後可直接開始拍攝或按「恢復待拍」。');if(t.status!=='pending')actions+=button('pending','恢復待拍','將工作重新放回待拍清單，原下單順位不變。');actions+='<label class="polaroid-round-change">調整時段<select data-task-round>'+roundOptions(id||t.roundId)+'</select></label><button class="btn ghost small" data-assign-round'+attrs+'>儲存時段</button>'}
      }else actions+=button('delivered','已完成並交付');
    }
    var order=session&&session.orders&&session.orders[t.orderId],orderTaskIds=Object.keys(order&&order.tasks||{}),canCancel=order&&order.status!=='cancelled'&&orderTaskIds[0]===t.taskId&&Object.values(order.tasks||{}).every(function(item){return['pending','deferred','no_show'].indexOf(item.status)!==-1});
    if(isManager&&canCancel)actions+='<button class="btn danger small" data-cancel-photo-order'+attrs+'>取消整張訂單</button>';
    if(isManager&&t.status!=='cancelled')actions+='<button class="btn ghost small" data-special-task'+attrs+'>特殊修改</button>';
    if(t.taskType==='shoot'&&!done(t)&&(isManager||ownsTask(t,staffId()))){actions+='<button class="btn ghost small" data-photo-macro'+attrs+' title="事前告知客人安排的拍攝輪次與時間">時段通知</button>';var due=taskIsDue(t);actions+='<button class="btn ghost small" data-photo-due-macro'+attrs+(due?'':' disabled title="尚未進入這筆訂單的拍攝時段"')+'>到時提醒</button>'}
    var when=t.taskType==='delivery'?'完成後交付':(id?roundLabel(id):'本場未完成／待店長安排'),clock=new Date(t.createdAt).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',second:'2-digit'});
    var notice=notificationState(t),dueNotice=dueNotificationState(t);return '<article class="polaroid-task '+(done(t)?'is-done':'')+'"><div class="polaroid-task-number">'+esc(t.taskNumber||'—')+'<small>'+esc(clock)+'</small></div><div><h4>'+esc(t.memberLabel||'未命名客人')+'｜'+esc(t.productName||t.maidName||'商品')+'</h4><p>'+esc(t.queueNumber||'')+'・'+esc(when)+'・'+esc(statusText(t.status))+'</p>'+(t.taskType==='shoot'&&t.status!=='cancelled'?'<p class="photo-notice-state '+(notice.outdated?'is-outdated':'')+'">時段通知：'+esc(notice.label)+'</p><p class="photo-notice-state due-state '+(dueNotice.outdated?'is-outdated':'')+'">到時提醒：'+esc(dueNotice.label)+'</p>':'')+(t.managerNote?'<p>店長備註：'+esc(t.managerNote)+'</p>':'')+'</div><div class="polaroid-task-actions">'+actions+'</div></article>';
  }
  function renderOverview(all){
    var rs=safeSlots(),time=timeNow(),current=rs.find(function(r){return r.start<=time&&time<r.end}),next=rs.find(function(r){return r.start>time}),shoot=all.filter(function(t){return t.taskType==='shoot'}),onsite=all.filter(function(t){return scheduler.onsiteTask(session||{},t)}),sold=session?scheduler.counts(session):{maids:{}},busy=new Set(shoot.filter(function(t){return t.status==='shooting'}).flatMap(scheduler.providers));
    el('polaroidCurrentRound').textContent=current?roundLabel(current.id):'目前非拍攝時段';el('polaroidNextRound').textContent=next?roundLabel(next.id):'無下一輪';el('polaroidBusyCount').textContent=busy.size+' / '+Number(session&&session.simultaneousMaids||2);
    el('polaroidMetricOrders').textContent=onsite.length;el('polaroidMetricDone').textContent=onsite.filter(done).length;el('polaroidMetricPending').textContent=onsite.filter(function(t){return!done(t)&&t.status!=='shooting'}).length;el('polaroidMetricDeferred').textContent=onsite.filter(function(t){return!done(t)}).length;
    el('polaroidMaidTotals').innerHTML=Object.entries(session&&session.maids||{}).filter(function(p){return p[1].enabled!==false||sold.maids[p[0]]}).map(function(p){var count=sold.maids[p[0]]||0,quota=scheduler.quota(session,p[0]);return '<div><strong>'+esc(p[1].name||staffName(p[0]))+'</strong><span>已接 '+count+' / '+quota+' 張・剩餘 '+Math.max(0,quota-count)+'</span></div>'}).join('');
    var closed=!session||session.isOpen===false||session.salesOpen===false||session.onsiteSalesOpen===false||!rs.some(function(r){return r.end>time});el('polaroidSessionBadge').textContent=closed?'拍攝服務已停止新登記':'拍攝服務接單中';el('polaroidSessionBadge').classList.toggle('open',!closed);
  }
  function renderDueTasks(all){var host=el('polaroidDueTasks');if(!host)return;var time=timeNow(),slot=safeSlots().find(function(r){return r.start<=time&&time<r.end}),due=slot?all.filter(function(t){return t.taskType==='shoot'&&!done(t)&&activeRound(t)===slot.id}):[];host.innerHTML=due.length?due.map(taskHtml).join(''):'<div class="queue-empty">'+(slot?'目前輪次沒有待通知的拍攝工作。':'目前不在任何拍攝輪次內。')+'</div>'}
  function render(){
    var badge=el('polaroidSessionBadge'),id=staffId(),all=tasks(),cancelled=all.filter(function(t){return t.status==='cancelled'}),current=all.filter(function(t){return t.status!=='cancelled'}),mine=id?current.filter(function(t){return ownsTask(t,id)}):[];
    badge.textContent=session?((session.salesOpen===false||session.onsiteSalesOpen===false)?'本場已停止新訂單':'本場接單中'):'尚未建立本場設定';badge.classList.toggle('open',!!session&&session.salesOpen!==false&&session.onsiteSalesOpen!==false);
    el('polaroidMyTitle').textContent=id?staffName(id)+'的拍立得工作':'我的拍立得工作';el('polaroidMyHint').textContent=id?('未完成 '+mine.filter(function(t){return!done(t)}).length+' 項・已完成 '+mine.filter(done).length+' 項'):'請先在上方選擇操作女僕。';el('polaroidMyTasks').innerHTML=mine.length?mine.filter(function(t){return!done(t)}).concat(mine.filter(done)).map(taskHtml).join(''):'<div class="queue-empty">'+(id?'目前沒有需要處理的拍立得工作。':'請先選擇操作女僕。')+'</div>';
    document.querySelectorAll('[data-polaroid-status]').forEach(function(b){b.classList.toggle('active',!!session&&id&&session.maids&&session.maids[id]&&session.maids[id].status===b.dataset.polaroidStatus)});
    var pending=current.filter(function(t){return!done(t)}).length,completed=current.filter(done).length,deferred=current.filter(function(t){return t.status==='deferred'||t.status==='no_show'}).length;el('navPolaroidCount').hidden=!pending;el('navPolaroidCount').textContent=pending;el('polaroidMetricOrders').textContent=current.length;el('polaroidMetricDone').textContent=completed;el('polaroidMetricPending').textContent=pending;el('polaroidMetricDeferred').textContent=deferred;el('polaroidAllTasks').innerHTML=current.length?current.filter(function(t){return!done(t)}).concat(current.filter(done)).map(taskHtml).join(''):'<div class="queue-empty">本場尚無需要處理的商品訂單。</div>';el('polaroidCancelledArchive').hidden=!cancelled.length;el('polaroidCancelledCount').textContent=cancelled.length;el('polaroidCancelledTasks').innerHTML=cancelled.map(taskHtml).join('');
    renderOverview(current);renderDueTasks(current);renderMacro();renderDueMacro();if(isManager){fillEditor();renderProductList();if(!el('polaroidProductId').value)fillProductStaffOptions()}window.dispatchEvent(new CustomEvent('polaroid-accounting-updated'));
  }
  function addRoundRow(value,id){var row=document.createElement('div');row.className='polaroid-round-row';row.dataset.id=id||('round_'+Date.now()+'_'+(++roundSeed));row.innerHTML='<label class="polaroid-round-field"><span>輪次名稱</span><input data-round-label maxlength="40" placeholder="例如：第一輪" value="'+esc(value&&value.label||'')+'"></label><label class="polaroid-round-field"><span>開始時間</span><input data-round-start type="time" value="'+esc(value&&value.startTime||'')+'"></label><label class="polaroid-round-field"><span>結束時間</span><input data-round-end type="time" value="'+esc(value&&value.endTime||'')+'"></label><button type="button" class="btn ghost small" data-remove-round>移除</button>';el('polaroidRoundEditor').appendChild(row)}
  function fillEditor(){if(el('polaroidSessionTitle').dataset.dirty==='1')return;el('polaroidSessionTitle').value=session&&session.title||'';el('polaroidBusinessDate').value=session&&session.businessDate||operation.businessDate||'';el('polaroidMaxProducts').value=session&&(session.maxProductsPerGuest||session.maxMaidsPerGuest)||5;el('polaroidSimultaneous').value=session&&session.simultaneousMaids||2;el('polaroidSessionOpen').checked=!session||session.isOpen!==false;el('polaroidSalesOpen').checked=!session||session.onsiteSalesOpen!==false;el('polaroidOtherSalesOpen').checked=!session||session.salesOpen!==false;el('polaroidRoundEditor').innerHTML='';var rs=rounds();if(rs.length)rs.forEach(function(r){addRoundRow(r[1],r[0])});else[['第一輪','21:40','22:00'],['第二輪','22:40','23:00'],['最後一輪','23:30','23:50']].forEach(function(r){addRoundRow({label:r[0],startTime:r[1],endTime:r[2]})});var maids=(session&&session.maids)||{};el('polaroidMaidEditor').innerHTML=Object.keys(roster).sort(function(a,b){return Number((roster[a]||{}).sortOrder||0)-Number((roster[b]||{}).sortOrder||0)}).map(function(id){var m=maids[id]||{},enabled=m.enabled===true;return'<div class="polaroid-maid-row" data-maid-row="'+esc(id)+'"><input data-maid-enabled type="checkbox" '+(enabled?'checked':'')+' aria-label="開放 '+esc(staffName(id))+'"><strong>'+esc(staffName(id))+'</strong><label>本場拍攝接單上限<input data-maid-quota type="number" min="0" max="100000" value="'+scheduler.quota(session||{},id)+'"></label></div>'}).join('')}
  function collect(){var roundsOut={},maids={};document.querySelectorAll('.polaroid-round-row').forEach(function(row,i){roundsOut[row.dataset.id]={label:row.querySelector('[data-round-label]').value.trim(),startTime:row.querySelector('[data-round-start]').value,endTime:row.querySelector('[data-round-end]').value,sortOrder:i*10}});document.querySelectorAll('[data-maid-row]').forEach(function(row,i){var id=row.dataset.maidRow,old=session&&session.maids&&session.maids[id]||{};maids[id]={name:staffName(id),imageUrl:old.imageUrl||'',enabled:row.querySelector('[data-maid-enabled]').checked,quota:Number(row.querySelector('[data-maid-quota]').value),sortOrder:i*10,status:old.status||'available',taskCounts:old.taskCounts||{}}});return{sessionId:operation.sessionId||sessionId,title:el('polaroidSessionTitle').value.trim(),businessDate:el('polaroidBusinessDate').value,isOpen:el('polaroidSessionOpen').checked,onsiteSalesOpen:el('polaroidSalesOpen').checked,salesOpen:el('polaroidOtherSalesOpen').checked,maxProductsPerGuest:Number(el('polaroidMaxProducts').value||5),simultaneousMaids:Number(el('polaroidSimultaneous').value||2),rounds:roundsOut,maids:maids,products:(session&&session.products)||{}}}
  function renderProductList(){var host=el('polaroidProductList'),items=products();host.innerHTML=items.length?items.map(function(p){var remaining=Number(p.stock)<0?'不限量':Math.max(0,Number(p.stock||0)-Number(p.sold||0))+' 份',thumb=p.imageUrl?'<img src="'+esc(p.imageUrl)+'" alt="">':'無圖片';return'<div class="polaroid-product-row"><div class="polaroid-product-thumb">'+thumb+'</div><div><strong>'+esc(p.name||'未命名商品')+'</strong><small>'+esc(p.category||'其他')+'・'+(p.processingMode==='delivery'?'完成後交付':'需要拍攝輪次')+'</small></div><div class="polaroid-product-meta">'+Number(p.price||0).toLocaleString('en-US')+' Gil</div><div class="polaroid-product-meta">本場剩餘 '+remaining+'</div><div class="polaroid-product-meta">'+(p.enabled===false?'已停賣':'販售中')+'</div><button class="btn ghost small" data-edit-product="'+esc(p.id)+'">編輯</button></div>'}).join(''):'<div class="queue-empty">尚未建立共用商品。請先儲存本場設定，再按「新增商品」建立第一項商品。</div>'}
  function staffOptions(selected){return'<option value="">請選擇</option>'+Object.keys(roster).sort(function(a,b){return staffName(a).localeCompare(staffName(b),'zh-Hant')}).map(function(id){return'<option value="'+esc(id)+'" '+(id===selected?'selected':'')+'>'+esc(staffName(id))+'</option>'}).join('')}
  function fillProductStaffOptions(){var current=el('polaroidProductProvider').value;el('polaroidProductProvider').innerHTML=staffOptions(current);var selected=list(editingProduct&&editingProduct.revenueMaidIds);el('polaroidProductRevenueMaids').innerHTML=Object.keys(roster).sort(function(a,b){return staffName(a).localeCompare(staffName(b),'zh-Hant')}).map(function(id){return'<option value="'+esc(id)+'" '+(selected.indexOf(id)!==-1?'selected':'')+'>'+esc(staffName(id))+'</option>'}).join('')}
  function addExampleRow(value){value=value||{};var row=document.createElement('div');row.className='polaroid-example-row';row.dataset.id=value.id||('example_'+Date.now()+'_'+(++exampleSeed));row.dataset.url=value.url||'';row.dataset.storagePath=value.storagePath||'';row.innerHTML=(value.url?'<img src="'+esc(value.url)+'" alt="">':'<div class="polaroid-product-thumb">新範例</div>')+'<label>圖片<input data-example-file type="file" accept="image/jpeg,image/png,image/webp"><span><input data-example-public type="checkbox" '+(value.enabled===false?'':'checked')+'> 公開顯示</span></label><label>標題與說明<input data-example-title type="text" maxlength="80" value="'+esc(value.title||'')+'" placeholder="範例標題"><textarea data-example-description maxlength="300" rows="2" placeholder="範例說明">'+esc(value.description||'')+'</textarea></label><div class="polaroid-example-actions"><button class="btn ghost small" data-remove-example type="button">移除</button></div>';el('polaroidExampleEditor').appendChild(row)}
  function resetProductEditor(){editingProduct=null;el('polaroidProductOnsite').checked=true;el('polaroidProductEditorTitle').textContent='新增商品';el('polaroidProductId').value='';el('polaroidProductName').value='';el('polaroidProductCategory').value='';el('polaroidProductPrice').value='80000';el('polaroidProductStock').value='3';el('polaroidProductLimit').value='1';el('polaroidProductMode').value='round';el('polaroidProductRevenue').value='maid';el('polaroidProductDescription').value='';el('polaroidProductEnabled').checked=true;el('polaroidProductImage').value='';el('polaroidProductImagePreview').textContent='尚未上傳封面';el('polaroidExampleEditor').innerHTML='';el('polaroidDeleteProduct').hidden=true;fillProductStaffOptions()}
  function editProduct(id){var p=products().find(function(x){return x.id===id});if(!p)return;editingProduct=p;el('polaroidProductOnsite').checked=scheduler.onsite(p);el('polaroidProductEditorTitle').textContent='編輯｜'+p.name;el('polaroidProductId').value=p.id;el('polaroidProductName').value=p.name||'';el('polaroidProductCategory').value=p.category||'';el('polaroidProductPrice').value=Number(p.price||0);el('polaroidProductStock').value=p.stock===undefined?-1:Number(p.stock);el('polaroidProductLimit').value=Number(p.perPersonLimit||1);el('polaroidProductMode').value=p.processingMode||'round';el('polaroidProductRevenue').value=p.revenueMode||'maid';el('polaroidProductDescription').value=p.description||'';el('polaroidProductEnabled').checked=p.enabled!==false;el('polaroidProductImage').value='';el('polaroidProductImagePreview').innerHTML=p.imageUrl?'<img src="'+esc(p.imageUrl)+'" alt="商品封面">':'尚未上傳封面';el('polaroidExampleEditor').innerHTML='';Object.values(p.examples||{}).sort(function(a,b){return Number(a.sortOrder||0)-Number(b.sortOrder||0)}).forEach(addExampleRow);el('polaroidDeleteProduct').hidden=false;fillProductStaffOptions();el('polaroidProductProvider').value=list(p.providerIds)[0]||'';Array.from(el('polaroidProductRevenueMaids').options).forEach(function(option){option.selected=list(p.revenueMaidIds).indexOf(option.value)!==-1});el('polaroidProductEditor').scrollIntoView({behavior:'smooth',block:'start'})}
  function upload(file,path){if(!file)return Promise.resolve(null);if(file.size>12*1024*1024)return Promise.reject(new Error('圖片不可超過 12 MB。'));return storage.ref(path).put(file,{contentType:file.type,cacheControl:'public,max-age=3600'}).then(function(s){return s.ref.getDownloadURL()}).then(function(url){return{url:url,storagePath:path}})}
  async function collectProduct(){var id=el('polaroidProductId').value||('product_'+Date.now()),base='polaroid-products/catalog/'+id,image={url:editingProduct&&editingProduct.imageUrl||'',storagePath:editingProduct&&editingProduct.imageStoragePath||''},file=el('polaroidProductImage').files[0];if(file)image=await upload(file,base+'/cover-'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_'));var examples={};for(var i=0;i<el('polaroidExampleEditor').children.length;i++){var row=el('polaroidExampleEditor').children[i],exampleFile=row.querySelector('[data-example-file]').files[0],media={url:row.dataset.url||'',storagePath:row.dataset.storagePath||''};if(exampleFile)media=await upload(exampleFile,base+'/examples/'+Date.now()+'-'+i+'-'+exampleFile.name.replace(/[^a-zA-Z0-9._-]/g,'_'));if(media&&media.url)examples[row.dataset.id]={id:row.dataset.id,url:media.url,storagePath:media.storagePath,title:row.querySelector('[data-example-title]').value.trim(),description:row.querySelector('[data-example-description]').value.trim(),enabled:row.querySelector('[data-example-public]').checked,sortOrder:i*10}}var provider=el('polaroidProductProvider').value,revenueIds=Array.from(el('polaroidProductRevenueMaids').selectedOptions).map(function(o){return o.value});if(el('polaroidProductRevenue').value==='maid'&&!revenueIds.length&&provider)revenueIds=[provider];return{isOnsitePhoto:el('polaroidProductOnsite').checked,id:id,name:el('polaroidProductName').value.trim(),category:el('polaroidProductCategory').value.trim(),price:Number(el('polaroidProductPrice').value||0),stock:Number(el('polaroidProductStock').value),perPersonLimit:Number(el('polaroidProductLimit').value||1),processingMode:el('polaroidProductOnsite').checked?'round':el('polaroidProductMode').value,providerIds:editingProduct&&list(editingProduct.providerIds).length>1?list(editingProduct.providerIds):provider?[provider]:[],revenueMode:el('polaroidProductRevenue').value,revenueMaidIds:revenueIds,description:el('polaroidProductDescription').value.trim(),enabled:el('polaroidProductEnabled').checked,imageUrl:image&&image.url||'',imageStoragePath:image&&image.storagePath||'',examples:examples,sortOrder:editingProduct?Number(editingProduct.sortOrder||0):products().length*10}}
  function watch(){if(sessionRef)sessionRef.off();var nextId=operation.sessionId||'';if(nextId!==sessionId){el('polaroidSessionTitle').dataset.dirty='';session=null}sessionId=nextId;if(!sessionId){session=null;render();return}sessionRef=db.ref('lephemere/polaroid/sessions/'+sessionId);sessionRef.on('value',function(s){session=s.val();render()})}
  firebase.auth().onAuthStateChanged(async function(user){if(!user)return;await checkRole(user);var snaps=await Promise.all([db.ref('lephemere/operationStatus').once('value'),db.ref('lephemere/staffRoster').once('value')]);operation=snaps[0].val()||{};roster=snaps[1].val()||{};watch()});db.ref('lephemere/operationStatus').on('value',function(s){operation=s.val()||{};watch()});db.ref('lephemere/staffRoster').on('value',function(s){roster=s.val()||{};render()});
  el('polaroidAdminTabs').addEventListener('click',function(e){var b=e.target.closest('[data-polaroid-pane]');if(!b||b.hasAttribute('data-manager-only')&&!isManager)return;document.querySelectorAll('[data-polaroid-pane]').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('[data-polaroid-panel]').forEach(function(x){x.hidden=x.dataset.polaroidPanel!==b.dataset.polaroidPane})});
  document.addEventListener('input',function(e){if(e.target.closest('[data-polaroid-panel="session"]'))el('polaroidSessionTitle').dataset.dirty='1'});
  document.addEventListener('change',function(e){if(e.target.id==='globalStaffSelect'){macroDirty=false;dueMacroDirty=false;render()}if(e.target.closest('[data-polaroid-panel="session"]'))el('polaroidSessionTitle').dataset.dirty='1'});
  el('polaroidAddRound').addEventListener('click',function(){addRoundRow();el('polaroidSessionTitle').dataset.dirty='1'});el('polaroidRoundEditor').addEventListener('click',function(e){if(e.target.matches('[data-remove-round]')){e.target.closest('.polaroid-round-row').remove();el('polaroidSessionTitle').dataset.dirty='1'}});
  el('polaroidStatusActions').addEventListener('click',function(e){var b=e.target.closest('[data-polaroid-status]'),id=staffId();if(!b||!id||!sessionId){alert('請先選擇操作女僕並建立本場設定。');return}setStatus({sessionId:sessionId,maidId:id,status:b.dataset.polaroidStatus}).catch(function(err){alert(err.message||'狀態更新失敗')})});
  function taskRecord(orderId,taskId){return session&&session.orders&&session.orders[orderId]&&session.orders[orderId].tasks&&session.orders[orderId].tasks[taskId]}
  function startsOutsideRound(task){var id=activeRound(task)||task.roundId,slot=safeSlots().find(function(row){return row.id===id}),time=timeNow();return !slot||time<slot.start||time>=slot.end}
  async function applySelectedRound(trigger){var id=staffId(),select=trigger.parentElement.querySelector('[data-task-round]');if(!select)return false;if(!select.value)throw new Error('請先選擇輪次。');var orderId=trigger.dataset.order,taskId=trigger.dataset.task,task=taskRecord(orderId,taskId),roundId=select.value;if(task&&(activeRound(task)||task.roundId)===roundId)return false;await assignRound({sessionId:sessionId,orderId:orderId,taskId:taskId,roundId:roundId,maidId:id||trigger.dataset.maid});if(task){task.originalRoundId=task.originalRoundId||task.roundId;task.roundId=roundId;task.awaitingArrangement=false}render();return true}
  el('polaroidTab').addEventListener('click',async function(e){var roundButton=e.target.closest('[data-assign-round]'),id=staffId();if(roundButton){if(!id&&!isManager){alert('請先選擇操作女僕。');return}roundButton.disabled=true;try{var changed=await applySelectedRound(roundButton);if(!changed&&roundButton.isConnected)roundButton.disabled=false}catch(err){alert(err.message||'輪次調整失敗');if(roundButton.isConnected)roundButton.disabled=false}return}var b=e.target.closest('[data-photo-action]');if(!b)return;if(!id&&!isManager){alert('請先選擇操作女僕。');return}var task=taskRecord(b.dataset.order,b.dataset.task);if(b.dataset.photoAction==='shooting'&&task&&startsOutsideRound(task)&&!confirm('目前不在這筆工作的安排時段內。\n若是測試或現場需要提早／延後拍攝，可以繼續，系統會保留紀錄。\n\n仍要開始拍攝嗎？'))return;b.disabled=true;updateTask({sessionId:sessionId,orderId:b.dataset.order,taskId:b.dataset.task,status:b.dataset.photoAction,maidId:id||b.dataset.maid}).catch(function(err){alert(err.message||'更新失敗');b.disabled=false})});
  el('polaroidSaveSession').addEventListener('click',function(){var status=el('polaroidSaveStatus'),data=collect();if(!data.sessionId){status.textContent='請先在「營業」開啟本次營業場次。';return}status.textContent='正在儲存…';this.disabled=true;saveSession(data).then(function(){status.textContent='本場設定已儲存。';el('polaroidSessionTitle').dataset.dirty='';fillEditor()}).catch(function(err){status.textContent=err.message||'儲存失敗'}).finally(function(){el('polaroidSaveSession').disabled=false})});
  el('polaroidNewProduct').addEventListener('click',resetProductEditor);el('polaroidProductList').addEventListener('click',function(e){var b=e.target.closest('[data-edit-product]');if(b)editProduct(b.dataset.editProduct)});el('polaroidAddExample').addEventListener('click',function(){addExampleRow()});el('polaroidExampleEditor').addEventListener('click',function(e){var b=e.target.closest('[data-remove-example]');if(b)b.closest('.polaroid-example-row').remove()});
  el('polaroidProductImage').addEventListener('change',function(){var file=this.files[0];if(file)el('polaroidProductImagePreview').innerHTML='<img src="'+URL.createObjectURL(file)+'" alt="封面預覽">'});
  el('polaroidSaveProduct').addEventListener('click',async function(){var status=el('polaroidProductStatus');if(!sessionId){status.textContent='請先建立本場設定。';return}if(!el('polaroidProductName').value.trim()){status.textContent='請填寫商品名稱。';return}if(!el('polaroidProductProvider').value){status.textContent='請選擇主要負責女僕。';return}this.disabled=true;status.textContent='正在上傳圖片並儲存…';try{var product=await collectProduct();await saveProduct({sessionId:sessionId,product:product});status.textContent='共用商品與範例已儲存，所有營業日期會使用這份資料。';editingProduct=product;el('polaroidProductId').value=product.id}catch(err){status.textContent=err.message||'儲存失敗'}finally{this.disabled=false}});
  el('polaroidDeleteProduct').addEventListener('click',function(){if(!editingProduct||!confirm('確定要在所有營業日期停止販售這項商品嗎？既有訂單不會消失。'))return;var status=el('polaroidProductStatus');this.disabled=true;deleteProduct({sessionId:sessionId,productId:editingProduct.id}).then(function(){status.textContent='共用商品已停止販售；歷史訂單仍保留。';resetProductEditor()}).catch(function(err){status.textContent=err.message||'刪除失敗'}).finally(function(){el('polaroidDeleteProduct').disabled=false})});
  var defaultPhotoMacro='/tell "{角色名}@{伺服器}" 主人您好，您預約的「{商品名}」安排於{輪次}（{開始時間}～{結束時間}）。請於時段前回到店內，等待期間可自由活動；如現場遞延會再通知您。—{女僕名}';
  function macroRows(){var id=staffId();return tasks().filter(function(t){return t.taskType==='shoot'&&!done(t)&&(isManager||ownsTask(t,id))})}
  var macroSignature='';
  function macroKey(t){var r=session&&session.rounds&&session.rounds[activeRound(t)]||{};return JSON.stringify([staffId(),t.orderId,t.taskId,activeRound(t),t.status,r.label,r.startTime,r.endTime,t.memberLabel,t.productName,t.queueNumber])}
  function macroVisibility(t){el('photoMacroMessage').hidden=!t;el('photoMacroCopy').disabled=!t;el('photoMacroMarkNotified').disabled=!t;el('photoMacroEmpty').hidden=!!t;if(!t){macroSignature='';el('photoMacroPreview').value='';el('photoMacroRound').textContent='';el('photoMacroNoticeState').textContent=''}else{var r=session&&session.rounds&&session.rounds[activeRound(t)]||{},notice=notificationState(t);el('photoMacroRound').textContent='目前安排：'+(r.label||'待店長安排')+'｜'+(r.startTime||'待安排')+'～'+(r.endTime||'待安排');el('photoMacroNoticeState').textContent=notice.label;el('photoMacroNoticeState').classList.toggle('is-outdated',notice.outdated)}}
  function makeMacro(){var t=macroRows().find(function(t){return t.orderId+'/'+t.taskId===el('photoMacroTask').value});macroVisibility(t);el('photoMacroStatus').textContent='';if(!t)return;macroSignature=macroKey(t);var parts=String(t.memberLabel||'').split('｜'),r=session&&session.rounds&&session.rounds[activeRound(t)]||{},vars={'角色名':parts[0]||'','伺服器':parts[1]||'','候位號碼':t.queueNumber||'','女僕名':staffName(staffId()||t.maidId),'商品名':t.productName||'','輪次':r.label||'待店長安排','開始時間':r.startTime||'待安排','結束時間':r.endTime||'待安排'};el('photoMacroPreview').value=el('photoMacroTemplate').value.replace(/\{([^}]+)\}/g,function(token,key){return Object.prototype.hasOwnProperty.call(vars,key)?String(vars[key]).replace(/[\r\n"]/g,''):token});if(!parts[1])el('photoMacroStatus').textContent='此角色未提供伺服器，請補上私訊對象再複製。'}
  function renderMacro(){var id=staffId(),selected=el('photoMacroTask').value;if(macroStaff!==id){macroStaff=id;macroDirty=false;el('photoMacroTemplate').value=(roster[id]||{}).photoCallTemplate||defaultPhotoMacro}if(!macroDirty&&document.activeElement!==el('photoMacroTemplate'))el('photoMacroTemplate').value=(roster[id]||{}).photoCallTemplate||defaultPhotoMacro;el('photoMacroSave').disabled=!id;var options=macroRows().map(function(t){return '<option value="'+esc(t.orderId+'/'+t.taskId)+'">'+esc((t.taskNumber||'')+' '+t.memberLabel+'｜'+t.productName)+'</option>'}).join('');el('photoMacroTask').innerHTML='<option value="">選擇待拍客人</option>'+options;el('photoMacroTask').value=selected;el('photoMacroTask').disabled=!options;el('photoMacroEmpty').textContent=options?'請先選擇客人，系統會帶入角色、商品及拍攝輪次時間。':'目前這位女僕沒有可通知的待拍客人；有訂單後會自動顯示。';if(!el('photoMacroTask').value)macroVisibility(null);else{var task=macroRows().find(function(t){return t.orderId+'/'+t.taskId===el('photoMacroTask').value});if(task&&macroSignature!==macroKey(task)){makeMacro();el('photoMacroStatus').textContent+=' 拍攝安排已更新，通知文字已重新帶入，請再次確認。'}}}
  el('photoMacroTemplate').addEventListener('input',function(){macroDirty=true;makeMacro()});el('photoMacroTask').addEventListener('change',makeMacro);
  el('photoMacroSave').addEventListener('click',async function(){this.disabled=true;try{await saveMacro({maidId:staffId(),template:el('photoMacroTemplate').value});macroDirty=false;el('photoMacroStatus').textContent='拍攝通知範本已儲存。'}catch(e){el('photoMacroStatus').textContent=e.message||'儲存失敗'}finally{this.disabled=false}});
  el('photoMacroCopy').addEventListener('click',async function(){var text=el('photoMacroPreview').value.trim();if(!text){el('photoMacroStatus').textContent='請先選擇客人。';return}try{await navigator.clipboard.writeText(text);el('photoMacroStatus').textContent='已複製，可貼到遊戲內私訊。'}catch(_){el('photoMacroPreview').select();el('photoMacroStatus').textContent='請按 Ctrl+C 複製選取文字。'}});
  el('photoMacroMarkNotified').addEventListener('click',async function(){var t=macroRows().find(function(row){return row.orderId+'/'+row.taskId===el('photoMacroTask').value}),id=staffId();if(!t||!id){el('photoMacroStatus').textContent='請先選擇操作女僕與通知客人。';return}this.disabled=true;try{await markNotified({sessionId:sessionId,orderId:t.orderId,taskId:t.taskId,maidId:id});el('photoMacroStatus').textContent='已記錄通知時間與操作女僕。'}catch(err){el('photoMacroStatus').textContent=err.message||'通知紀錄失敗';this.disabled=false}});
  var defaultDuePhotoMacro='/tell "{角色名}@{伺服器}" 主人您好，現在已到您預約「{商品名}」的拍攝時段（{輪次} {開始時間}～{結束時間}），請回到店內並告知女僕，我們將依現場順序為您安排。—{女僕名}';
  function dueMacroRows(){var id=staffId();return macroRows().filter(function(t){return taskIsDue(t)&&(isManager||ownsTask(t,id))})}
  function dueMacroVisibility(t){el('photoDueMacroMessage').hidden=!t;el('photoDueMacroCopy').disabled=!t;el('photoDueMacroMarkNotified').disabled=!t;el('photoDueMacroEmpty').hidden=!!t;if(!t){el('photoDueMacroPreview').value='';el('photoDueMacroRound').textContent='';el('photoDueMacroNoticeState').textContent=''}else{var r=session&&session.rounds&&session.rounds[activeRound(t)]||{},notice=dueNotificationState(t);el('photoDueMacroRound').textContent='目前時段：'+(r.label||'待安排')+'｜'+(r.startTime||'')+'～'+(r.endTime||'');el('photoDueMacroNoticeState').textContent=notice.label;el('photoDueMacroNoticeState').classList.toggle('is-outdated',notice.outdated)}}
  function makeDueMacro(){var t=dueMacroRows().find(function(row){return row.orderId+'/'+row.taskId===el('photoDueMacroTask').value});dueMacroVisibility(t);el('photoDueMacroStatus').textContent='';if(!t)return;var parts=String(t.memberLabel||'').split('｜'),r=session&&session.rounds&&session.rounds[activeRound(t)]||{},vars={'角色名':parts[0]||'','伺服器':parts[1]||'','候位號碼':t.queueNumber||'','女僕名':staffName(staffId()||t.maidId),'商品名':t.productName||'','輪次':r.label||'待安排','開始時間':r.startTime||'','結束時間':r.endTime||''};el('photoDueMacroPreview').value=el('photoDueMacroTemplate').value.replace(/\{([^}]+)\}/g,function(token,key){return Object.prototype.hasOwnProperty.call(vars,key)?String(vars[key]).replace(/[\r\n"]/g,''):token});if(!parts[1])el('photoDueMacroStatus').textContent='此角色未提供伺服器，請補上私訊對象再複製。'}
  function renderDueMacro(){var id=staffId(),selected=el('photoDueMacroTask').value;if(dueMacroStaff!==id){dueMacroStaff=id;dueMacroDirty=false;el('photoDueMacroTemplate').value=(roster[id]||{}).photoDueTemplate||defaultDuePhotoMacro}if(!dueMacroDirty&&document.activeElement!==el('photoDueMacroTemplate'))el('photoDueMacroTemplate').value=(roster[id]||{}).photoDueTemplate||defaultDuePhotoMacro;el('photoDueMacroSave').disabled=!id;var options=dueMacroRows().map(function(t){return '<option value="'+esc(t.orderId+'/'+t.taskId)+'">'+esc((t.taskNumber||'')+' '+t.memberLabel+'｜'+t.productName)+'</option>'}).join('');el('photoDueMacroTask').innerHTML='<option value="">選擇已到時段的客人</option>'+options;el('photoDueMacroTask').value=selected;el('photoDueMacroTask').disabled=!options;el('photoDueMacroEmpty').textContent=options?'請選擇客人，系統會產生與時段通知不同的到時提醒。':(currentSlot()?'目前時段沒有需要提醒的拍攝客人。':'目前不在任何拍攝輪次內。');if(!el('photoDueMacroTask').value)dueMacroVisibility(null);else makeDueMacro()}
  el('photoDueMacroTemplate').addEventListener('input',function(){dueMacroDirty=true;makeDueMacro()});el('photoDueMacroTask').addEventListener('change',makeDueMacro);
  el('photoDueMacroSave').addEventListener('click',async function(){this.disabled=true;try{await saveMacro({maidId:staffId(),kind:'due',template:el('photoDueMacroTemplate').value});dueMacroDirty=false;el('photoDueMacroStatus').textContent='到時提醒範本已儲存。'}catch(e){el('photoDueMacroStatus').textContent=e.message||'儲存失敗'}finally{this.disabled=false}});
  el('photoDueMacroCopy').addEventListener('click',async function(){var text=el('photoDueMacroPreview').value.trim();if(!text){el('photoDueMacroStatus').textContent='請先選擇目前時段客人。';return}try{await navigator.clipboard.writeText(text);el('photoDueMacroStatus').textContent='到時提醒已複製，可貼到遊戲內私訊。'}catch(_){el('photoDueMacroPreview').select();el('photoDueMacroStatus').textContent='請按 Ctrl+C 複製選取文字。'}});
  el('photoDueMacroMarkNotified').addEventListener('click',async function(){var t=dueMacroRows().find(function(row){return row.orderId+'/'+row.taskId===el('photoDueMacroTask').value}),id=staffId();if(!t||!id){el('photoDueMacroStatus').textContent='請先選擇操作女僕與目前時段客人。';return}this.disabled=true;try{await markNotified({sessionId:sessionId,orderId:t.orderId,taskId:t.taskId,maidId:id,notificationType:'due'});el('photoDueMacroStatus').textContent='已記錄到時提醒時間與操作女僕。'}catch(err){el('photoDueMacroStatus').textContent=err.message||'提醒紀錄失敗';this.disabled=false}});
  el('polaroidTab').addEventListener('click',async function(e){
    var cancel=e.target.closest('[data-cancel-photo-order]');if(cancel&&isManager){var order=session&&session.orders&&session.orders[cancel.dataset.order];if(!order)return;var itemCount=Object.keys(order.tasks||{}).length;if(!confirm('確定取消這張訂單的全部 '+itemCount+' 項商品嗎？\n取消後會歸還商品庫存與女僕名額，並從本場收入排除。'))return;var reason=prompt('請填寫取消原因（會保留在操作紀錄）：','測試訂單');if(!reason||!reason.trim())return;cancel.disabled=true;try{await cancelOrder({sessionId:sessionId,orderId:cancel.dataset.order,reason:reason.trim()})}catch(err){alert(err.message||'取消訂單失敗');cancel.disabled=false}return}
    var macro=e.target.closest('[data-photo-macro]');if(macro){var orderId=macro.dataset.order,taskId=macro.dataset.task;macro.disabled=true;try{await applySelectedRound(macro);var nav=document.querySelector('[data-main="macros"]');if(nav)nav.click();renderMacro();el('photoMacroTask').value=orderId+'/'+taskId;makeMacro();el('photoMacroStatus').textContent='已依工作列選擇的輪次更新通知時間。';el('photoMacroPreview').focus()}catch(err){alert(err.message||'輪次調整失敗，尚未開啟通知巨集。')}return}
    var dueMacro=e.target.closest('[data-photo-due-macro]');if(dueMacro){var dueOrderId=dueMacro.dataset.order,dueTaskId=dueMacro.dataset.task,navDue=document.querySelector('[data-main="macros"]');if(navDue)navDue.click();renderDueMacro();el('photoDueMacroTask').value=dueOrderId+'/'+dueTaskId;makeDueMacro();el('photoDueMacroPreview').focus();return}
    var special=e.target.closest('[data-special-task]');if(!special||!isManager)return;var action=prompt('特殊修改：輸入 1 補充備註、2 恢復待拍、3 人工確認完成。\n不變更購買內容、金額或原始順位。','1');if(action===null)return;var map={'1':'note','2':'pending','3':'completed'};if(!map[action]){alert('請輸入 1、2 或 3。');return}var note=prompt('請填寫修改原因（保留操作紀錄）：');if(!note||!note.trim())return;special.disabled=true;try{await specialTask({sessionId:sessionId,orderId:special.dataset.order,taskId:special.dataset.task,action:map[action],note:note})}catch(err){alert(err.message||'修改失敗')}finally{special.disabled=false}
  });
  db.ref('.info/serverTimeOffset').on('value',function(s){clockOffset=Number(s.val()||0)});
  var lastRoundSignature='';
  setInterval(function(){if(!session)return;var all=tasks().filter(function(t){return t.status!=='cancelled'}),signature=all.map(function(t){return t.taskId+':'+activeRound(t)}).join('|');renderOverview(all);renderDueTasks(all);renderDueMacro();if(signature!==lastRoundSignature){lastRoundSignature=signature;renderMacro();el('polaroidAllTasks').innerHTML=all.filter(function(t){return!done(t)}).concat(all.filter(done)).map(taskHtml).join('');var mine=all.filter(function(t){return ownsTask(t,staffId())});el('polaroidMyTasks').innerHTML=mine.filter(function(t){return!done(t)}).concat(mine.filter(done)).map(taskHtml).join('')}
  },15000);

  resetProductEditor();
})();
