(function(){
  'use strict';
  if(!window.firebase||!firebase.apps.length)return;
  var db=firebase.database(),fn=firebase.app().functions('asia-southeast1'),saveSession=fn.httpsCallable('polaroidSaveSession'),setStatus=fn.httpsCallable('polaroidSetMaidStatus'),updateTask=fn.httpsCallable('polaroidUpdateTask');
  var session=null,sessionId='',operation={},roster={},isManager=false,sessionRef=null,roundSeed=0;
  function el(id){return document.getElementById(id)} function esc(v){var d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML} function staffId(){try{return localStorage.getItem('lephemereCurrentStaffId')||''}catch(_){return''}} function staffName(id){return(roster[id]||{}).name||'未命名女僕'}
  async function checkRole(user){if(!user)return;var values=await Promise.all([db.ref('lephemere/todayStaff/_access/ownerUid').once('value'),db.ref('lephemere/todayStaff/_access/users/'+user.uid+'/role').once('value')]),role=values[1].val()||'';isManager=String(user.email||'').toLowerCase()==='tanjicafe@gmail.com'||values[0].val()===user.uid||role==='manager'}
  function rounds(){return Object.entries((session&&session.rounds)||{}).sort(function(a,b){return Number(a[1].sortOrder||0)-Number(b[1].sortOrder||0)})} function roundLabel(id){var r=session&&session.rounds&&session.rounds[id];return r?((r.label||'')+' '+(r.startTime||'')+(r.endTime?'–'+r.endTime:'')):'尚未安排'}
  function tasks(){var out=[];Object.entries((session&&session.orders)||{}).forEach(function(pair){var oid=pair[0],o=pair[1]||{};Object.entries(o.tasks||{}).forEach(function(tp){out.push(Object.assign({orderId:oid,taskId:tp[0],ownerUid:o.ownerUid},tp[1]||{}))})});return out.sort(function(a,b){return Number(a.createdAt||0)-Number(b.createdAt||0)})}
  window.LephemerePolaroidAccounting=function(date){var result={orderCount:0,total:0,taskCount:0,completed:0,deferred:0,specialByStaff:{},staffNames:{}};if(!session||String(session.businessDate||'')!==String(date||''))return result;Object.values(session.orders||{}).forEach(function(order){if(!order||order.status!=='paid')return;result.orderCount++;result.total+=Number(order.total||0);Object.values(order.tasks||{}).forEach(function(task){if(!task)return;var price=Number(task.price!==undefined?task.price:(session.maids&&session.maids[task.maidId]&&session.maids[task.maidId].price)||0);result.taskCount++;if(task.status==='completed')result.completed++;if(task.status==='deferred'||task.status==='no_show')result.deferred++;if(task.maidId){result.specialByStaff[task.maidId]=(result.specialByStaff[task.maidId]||0)+price;result.staffNames[task.maidId]=task.maidName||staffName(task.maidId)}})});return result};
  function statusText(s){return{pending:'等待拍攝',completed:'已完成',deferred:'順延',no_show:'未到場'}[s]||s}
  function taskHtml(t,own){var actions='';if(t.status!=='completed'){actions='<div class="polaroid-task-actions"><button class="btn primary small" data-photo-action="completed" data-order="'+esc(t.orderId)+'" data-task="'+esc(t.taskId)+'" data-maid="'+esc(t.maidId)+'">拍攝完成</button><button class="btn ghost small" data-photo-action="deferred" data-order="'+esc(t.orderId)+'" data-task="'+esc(t.taskId)+'" data-maid="'+esc(t.maidId)+'">未到場／順延</button></div>'}return'<article class="polaroid-task '+(t.status==='completed'?'is-done':'')+'"><div class="polaroid-task-number">'+esc(t.taskNumber||'—')+'</div><div><h4>'+esc(t.memberLabel||'未命名客人')+'・'+esc(t.queueNumber||'')+'</h4><p>'+esc(t.maidName)+'・'+esc(roundLabel(t.roundId))+'・'+esc(statusText(t.status))+'</p></div>'+actions+'</article>'}
  function render(){var badge=el('polaroidSessionBadge'),id=staffId(),all=tasks(),mine=id?all.filter(function(t){return t.maidId===id&&t.status!=='completed'}):[];badge.textContent=session?(session.onsiteSalesOpen?'本場接單中':'本場已停止新接單'):'尚未建立本場設定';badge.classList.toggle('open',!!session&&session.onsiteSalesOpen===true);el('polaroidMyTitle').textContent=id?staffName(id)+'的待拍清單':'我的待拍';el('polaroidMyHint').textContent=id?('目前 '+mine.length+' 位等待處理'):'請先在上方選擇操作女僕。';el('polaroidMyTasks').innerHTML=mine.length?mine.map(function(t){return taskHtml(t,true)}).join(''):'<div class="queue-empty">'+(id?'目前沒有待拍項目。':'請先選擇操作女僕。')+'</div>';document.querySelectorAll('[data-polaroid-status]').forEach(function(b){b.classList.toggle('active',!!session&&id&&session.maids&&session.maids[id]&&session.maids[id].status===b.dataset.polaroidStatus)});var pending=all.filter(function(t){return t.status==='pending'}).length,done=all.filter(function(t){return t.status==='completed'}).length,deferred=all.filter(function(t){return t.status==='deferred'||t.status==='no_show'}).length;el('navPolaroidCount').hidden=!pending;el('navPolaroidCount').textContent=pending;el('polaroidMetricOrders').textContent=Object.keys((session&&session.orders)||{}).length;el('polaroidMetricDone').textContent=done;el('polaroidMetricPending').textContent=pending;el('polaroidMetricDeferred').textContent=deferred;el('polaroidAllTasks').innerHTML=all.length?all.map(function(t){return taskHtml(t,false)}).join(''):'<div class="queue-empty">本場尚無拍立得訂單。</div>';if(isManager)fillEditor();window.dispatchEvent(new CustomEvent('polaroid-accounting-updated'))}
  function addRoundRow(value,id){var row=document.createElement('div');row.className='polaroid-round-row';row.dataset.id=id||('round_'+Date.now()+'_'+(++roundSeed));row.innerHTML='<input data-round-label maxlength="40" placeholder="例如：第一輪" value="'+esc(value&&value.label||'')+'"><input data-round-start type="time" value="'+esc(value&&value.startTime||'')+'"><input data-round-end type="time" value="'+esc(value&&value.endTime||'')+'"><button type="button" class="btn ghost small" data-remove-round>移除</button>';el('polaroidRoundEditor').appendChild(row)}
  function fillEditor(){if(el('polaroidSessionTitle').dataset.dirty==='1')return;el('polaroidSessionTitle').value=session&&session.title||'';el('polaroidBusinessDate').value=session&&session.businessDate||operation.businessDate||'';el('polaroidMaxMaids').value=session&&session.maxMaidsPerGuest||3;el('polaroidPerMaidLimit').value=session&&session.perMaidPerGuestLimit||1;el('polaroidSimultaneous').value=session&&session.simultaneousMaids||2;el('polaroidSessionOpen').checked=!session||session.isOpen!==false;el('polaroidSalesOpen').checked=!session||session.onsiteSalesOpen!==false;el('polaroidRoundEditor').innerHTML='';var rs=rounds();if(rs.length)rs.forEach(function(r){addRoundRow(r[1],r[0])});else[['第一輪','21:40','22:00'],['第二輪','22:40','23:00'],['最後一輪','23:30','23:50']].forEach(function(r){addRoundRow({label:r[0],startTime:r[1],endTime:r[2]})});var maids=(session&&session.maids)||{};el('polaroidMaidEditor').innerHTML=Object.keys(roster).sort(function(a,b){return Number((roster[a]||{}).sortOrder||0)-Number((roster[b]||{}).sortOrder||0)}).map(function(id){var m=maids[id]||{},enabled=m.enabled===true;return'<div class="polaroid-maid-row" data-maid-row="'+esc(id)+'"><input data-maid-enabled type="checkbox" '+(enabled?'checked':'')+' aria-label="開放 '+esc(staffName(id))+'"><strong>'+esc(staffName(id))+'</strong><label>價格<input data-maid-price type="number" min="0" step="10000" value="'+Number(m.price||80000)+'"></label><label>總名額<input data-maid-quota type="number" min="0" value="'+Number(m.quota||10)+'"></label></div>'}).join('')}
  function collect(){var roundsOut={},maids={};document.querySelectorAll('.polaroid-round-row').forEach(function(row,i){roundsOut[row.dataset.id]={label:row.querySelector('[data-round-label]').value.trim(),startTime:row.querySelector('[data-round-start]').value,endTime:row.querySelector('[data-round-end]').value,sortOrder:i*10}});document.querySelectorAll('[data-maid-row]').forEach(function(row,i){var id=row.dataset.maidRow,old=session&&session.maids&&session.maids[id]||{};maids[id]={name:staffName(id),imageUrl:old.imageUrl||'',price:Number(row.querySelector('[data-maid-price]').value||0),quota:Number(row.querySelector('[data-maid-quota]').value||0),enabled:row.querySelector('[data-maid-enabled]').checked,sortOrder:i*10}});return{sessionId:operation.sessionId||sessionId,title:el('polaroidSessionTitle').value.trim(),businessDate:el('polaroidBusinessDate').value,isOpen:el('polaroidSessionOpen').checked,onsiteSalesOpen:el('polaroidSalesOpen').checked,maxMaidsPerGuest:Number(el('polaroidMaxMaids').value||3),perMaidPerGuestLimit:Number(el('polaroidPerMaidLimit').value||1),simultaneousMaids:Number(el('polaroidSimultaneous').value||2),rounds:roundsOut,maids:maids}}
  function watch(){if(sessionRef)sessionRef.off();sessionId=operation.sessionId||'';if(!sessionId){session=null;render();return}sessionRef=db.ref('lephemere/polaroid/sessions/'+sessionId);sessionRef.on('value',function(s){session=s.val();el('polaroidSessionTitle').dataset.dirty='';render()})}
  firebase.auth().onAuthStateChanged(async function(user){if(!user)return;await checkRole(user);var snaps=await Promise.all([db.ref('lephemere/operationStatus').once('value'),db.ref('lephemere/staffRoster').once('value')]);operation=snaps[0].val()||{};roster=snaps[1].val()||{};watch()});db.ref('lephemere/operationStatus').on('value',function(s){operation=s.val()||{};watch()});db.ref('lephemere/staffRoster').on('value',function(s){roster=s.val()||{};render()});
  document.addEventListener('change',function(e){if(e.target.id==='globalStaffSelect')render();if(e.target.closest('#polaroidManagerArea'))el('polaroidSessionTitle').dataset.dirty='1'});el('polaroidAddRound').addEventListener('click',function(){addRoundRow();el('polaroidSessionTitle').dataset.dirty='1'});el('polaroidRoundEditor').addEventListener('click',function(e){if(e.target.matches('[data-remove-round]')){e.target.closest('.polaroid-round-row').remove();el('polaroidSessionTitle').dataset.dirty='1'}});
  el('polaroidStatusActions').addEventListener('click',function(e){var b=e.target.closest('[data-polaroid-status]'),id=staffId();if(!b||!id||!sessionId){alert('請先選擇操作女僕並建立本場設定。');return}setStatus({sessionId:sessionId,maidId:id,status:b.dataset.polaroidStatus}).catch(function(err){alert(err.message||'狀態更新失敗')})});
  el('polaroidTab').addEventListener('click',function(e){var b=e.target.closest('[data-photo-action]');if(!b)return;var id=staffId();if(!id&&!isManager){alert('請先選擇操作女僕。');return}b.disabled=true;updateTask({sessionId:sessionId,orderId:b.dataset.order,taskId:b.dataset.task,status:b.dataset.photoAction,maidId:id||b.dataset.maid}).catch(function(err){alert(err.message||'更新失敗');b.disabled=false})});
  el('polaroidSaveSession').addEventListener('click',function(){var status=el('polaroidSaveStatus'),data=collect();if(!data.sessionId){status.textContent='請先在「營業」開啟本次營業場次。';return}status.textContent='正在儲存…';this.disabled=true;saveSession(data).then(function(){status.textContent='本場拍立得設定已儲存。';el('polaroidSessionTitle').dataset.dirty=''}).catch(function(err){status.textContent=err.message||'儲存失敗'}).finally(function(){el('polaroidSaveSession').disabled=false})});
})();
