(function(){
  'use strict';
  if(!window.firebase||!firebase.apps.length)return;
  var db=firebase.database(),storage=firebase.storage(),fn=firebase.app().functions('asia-southeast1');
  var saveSession=fn.httpsCallable('polaroidSaveSession'),saveProduct=fn.httpsCallable('polaroidSaveProduct'),deleteProduct=fn.httpsCallable('polaroidDeleteProduct'),setStatus=fn.httpsCallable('polaroidSetMaidStatus'),updateTask=fn.httpsCallable('polaroidUpdateTask');
  var session=null,sessionId='',operation={},roster={},isManager=false,sessionRef=null,roundSeed=0,exampleSeed=0,editingProduct=null;
  function el(id){return document.getElementById(id)}
  function esc(v){var d=document.createElement('div');d.textContent=String(v==null?'':v);return d.innerHTML}
  function staffId(){try{return localStorage.getItem('lephemereCurrentStaffId')||''}catch(_){return''}}
  function staffName(id){return(roster[id]||{}).name||'未命名女僕'}
  function list(v){return Array.isArray(v)?v:Object.values(v||{})}
  function done(t){return t.status==='completed'||t.status==='delivered'}
  async function checkRole(user){if(!user)return;var values=await Promise.all([db.ref('lephemere/todayStaff/_access/ownerUid').once('value'),db.ref('lephemere/todayStaff/_access/users/'+user.uid+'/role').once('value')]),role=values[1].val()||'';isManager=String(user.email||'').toLowerCase()==='tanjicafe@gmail.com'||values[0].val()===user.uid||role==='manager'}
  function rounds(){return Object.entries((session&&session.rounds)||{}).sort(function(a,b){return Number(a[1].sortOrder||0)-Number(b[1].sortOrder||0)})}
  function products(){return Object.entries((session&&session.products)||{}).map(function(pair){return Object.assign({id:pair[0]},pair[1]||{})}).sort(function(a,b){return Number(a.sortOrder||0)-Number(b.sortOrder||0)})}
  function roundLabel(id){var r=session&&session.rounds&&session.rounds[id];return r?((r.label||'')+' '+(r.startTime||'')+(r.endTime?'–'+r.endTime:'')):'不需輪次'}
  function tasks(){var out=[];Object.entries((session&&session.orders)||{}).forEach(function(pair){var oid=pair[0],o=pair[1]||{};Object.entries(o.tasks||{}).forEach(function(tp){out.push(Object.assign({orderId:oid,taskId:tp[0],ownerUid:o.ownerUid},tp[1]||{}))})});return out.sort(function(a,b){return Number(a.createdAt||0)-Number(b.createdAt||0)})}
  window.LephemerePolaroidAccounting=function(date){var result={orderCount:0,total:0,taskCount:0,completed:0,deferred:0,commonRevenue:0,personalRevenue:0,unassignedRevenue:0,specialByStaff:{},staffNames:{}};if(!session||String(session.businessDate||'')!==String(date||''))return result;Object.values(session.orders||{}).forEach(function(order){if(!order||['paid','completed'].indexOf(order.status)===-1)return;result.orderCount++;result.total+=Number(order.total||0);Object.values(order.tasks||{}).forEach(function(task){if(!task)return;var price=Number(task.price||0),ids=list(task.revenueMaidIds).filter(Boolean);result.taskCount++;if(done(task))result.completed++;if(task.status==='deferred'||task.status==='no_show')result.deferred++;if(task.revenueMode==='shared'){result.commonRevenue+=price;return}if(task.revenueMode==='maid'&&ids.length>1)ids=ids.slice(0,1);if(!ids.length&&task.maidId)ids=[task.maidId];if(!ids.length){result.unassignedRevenue+=price;return}var share=price/ids.length;ids.forEach(function(id){result.specialByStaff[id]=(result.specialByStaff[id]||0)+share;result.staffNames[id]=staffName(id)});result.personalRevenue+=price})});return result};
  function statusText(s){return{pending:'等待處理',completed:'拍攝完成',delivered:'已完成並交付',deferred:'順延',no_show:'未到場'}[s]||s}
  function ownsTask(t,id){return t.maidId===id||list(t.providerIds).indexOf(id)!==-1}
  function taskHtml(t){var action=t.taskType==='delivery'?'delivered':'completed',label=t.taskType==='delivery'?'已完成並交付':'拍攝完成',actions='';if(!done(t)){actions='<div class="polaroid-task-actions"><button class="btn primary small" data-photo-action="'+action+'" data-order="'+esc(t.orderId)+'" data-task="'+esc(t.taskId)+'" data-maid="'+esc(t.maidId)+'">'+label+'</button>'+(t.taskType==='shoot'?'<button class="btn ghost small" data-photo-action="deferred" data-order="'+esc(t.orderId)+'" data-task="'+esc(t.taskId)+'" data-maid="'+esc(t.maidId)+'">未到場／順延</button>':'')+'</div>'}return'<article class="polaroid-task '+(done(t)?'is-done':'')+'"><div class="polaroid-task-number">'+esc(t.taskNumber||'—')+'</div><div><h4>'+esc(t.memberLabel||'未命名客人')+'｜'+esc(t.productName||t.maidName||'拍立得商品')+'</h4><p>'+esc(t.queueNumber||'')+'・'+esc(t.taskType==='delivery'?'完成後交付':roundLabel(t.roundId))+'・'+esc(statusText(t.status))+'</p><span class="polaroid-task-type">'+(t.taskType==='delivery'?'商品交付':'拍攝輪次')+'</span></div>'+actions+'</article>'}
  function render(){
    var badge=el('polaroidSessionBadge'),id=staffId(),all=tasks(),mine=id?all.filter(function(t){return ownsTask(t,id)&&!done(t)}):[];
    badge.textContent=session?((session.salesOpen===false||session.onsiteSalesOpen===false)?'本場已停止新訂單':'本場接單中'):'尚未建立本場設定';badge.classList.toggle('open',!!session&&session.salesOpen!==false&&session.onsiteSalesOpen!==false);
    el('polaroidMyTitle').textContent=id?staffName(id)+'的拍立得工作':'我的拍立得工作';el('polaroidMyHint').textContent=id?('目前 '+mine.length+' 項等待處理'):'請先在上方選擇操作女僕。';el('polaroidMyTasks').innerHTML=mine.length?mine.map(taskHtml).join(''):'<div class="queue-empty">'+(id?'目前沒有需要處理的拍立得工作。':'請先選擇操作女僕。')+'</div>';
    document.querySelectorAll('[data-polaroid-status]').forEach(function(b){b.classList.toggle('active',!!session&&id&&session.maids&&session.maids[id]&&session.maids[id].status===b.dataset.polaroidStatus)});
    var pending=all.filter(function(t){return!done(t)}).length,completed=all.filter(done).length,deferred=all.filter(function(t){return t.status==='deferred'||t.status==='no_show'}).length;el('navPolaroidCount').hidden=!pending;el('navPolaroidCount').textContent=pending;el('polaroidMetricOrders').textContent=Object.keys((session&&session.orders)||{}).length;el('polaroidMetricDone').textContent=completed;el('polaroidMetricPending').textContent=pending;el('polaroidMetricDeferred').textContent=deferred;el('polaroidAllTasks').innerHTML=all.length?all.map(taskHtml).join(''):'<div class="queue-empty">本場尚無拍立得商品訂單。</div>';
    if(isManager){fillEditor();renderProductList();fillProductStaffOptions()}window.dispatchEvent(new CustomEvent('polaroid-accounting-updated'));
  }
  function addRoundRow(value,id){var row=document.createElement('div');row.className='polaroid-round-row';row.dataset.id=id||('round_'+Date.now()+'_'+(++roundSeed));row.innerHTML='<input data-round-label maxlength="40" placeholder="例如：第一輪" value="'+esc(value&&value.label||'')+'"><input data-round-start type="time" value="'+esc(value&&value.startTime||'')+'"><input data-round-end type="time" value="'+esc(value&&value.endTime||'')+'"><button type="button" class="btn ghost small" data-remove-round>移除</button>';el('polaroidRoundEditor').appendChild(row)}
  function fillEditor(){if(el('polaroidSessionTitle').dataset.dirty==='1')return;el('polaroidSessionTitle').value=session&&session.title||'';el('polaroidBusinessDate').value=session&&session.businessDate||operation.businessDate||'';el('polaroidMaxProducts').value=session&&(session.maxProductsPerGuest||session.maxMaidsPerGuest)||5;el('polaroidSimultaneous').value=session&&session.simultaneousMaids||2;el('polaroidSessionOpen').checked=!session||session.isOpen!==false;el('polaroidSalesOpen').checked=!session||session.salesOpen!==false&&session.onsiteSalesOpen!==false;el('polaroidRoundEditor').innerHTML='';var rs=rounds();if(rs.length)rs.forEach(function(r){addRoundRow(r[1],r[0])});else[['第一輪','21:40','22:00'],['第二輪','22:40','23:00'],['最後一輪','23:30','23:50']].forEach(function(r){addRoundRow({label:r[0],startTime:r[1],endTime:r[2]})});var maids=(session&&session.maids)||{};el('polaroidMaidEditor').innerHTML=Object.keys(roster).sort(function(a,b){return Number((roster[a]||{}).sortOrder||0)-Number((roster[b]||{}).sortOrder||0)}).map(function(id){var m=maids[id]||{},enabled=m.enabled===true;return'<div class="polaroid-maid-row" data-maid-row="'+esc(id)+'"><input data-maid-enabled type="checkbox" '+(enabled?'checked':'')+' aria-label="開放 '+esc(staffName(id))+'"><strong>'+esc(staffName(id))+'</strong><span>'+esc({available:'可拍',serving:'接待中',shooting:'拍攝中',away:'暫離',off:'下班'}[m.status]||'尚未設定')+'</span></div>'}).join('')}
  function collect(){var roundsOut={},maids={};document.querySelectorAll('.polaroid-round-row').forEach(function(row,i){roundsOut[row.dataset.id]={label:row.querySelector('[data-round-label]').value.trim(),startTime:row.querySelector('[data-round-start]').value,endTime:row.querySelector('[data-round-end]').value,sortOrder:i*10}});document.querySelectorAll('[data-maid-row]').forEach(function(row,i){var id=row.dataset.maidRow,old=session&&session.maids&&session.maids[id]||{};maids[id]={name:staffName(id),imageUrl:old.imageUrl||'',enabled:row.querySelector('[data-maid-enabled]').checked,sortOrder:i*10,status:old.status||'available',taskCounts:old.taskCounts||{}}});return{sessionId:operation.sessionId||sessionId,title:el('polaroidSessionTitle').value.trim(),businessDate:el('polaroidBusinessDate').value,isOpen:el('polaroidSessionOpen').checked,salesOpen:el('polaroidSalesOpen').checked,maxProductsPerGuest:Number(el('polaroidMaxProducts').value||5),simultaneousMaids:Number(el('polaroidSimultaneous').value||2),rounds:roundsOut,maids:maids,products:(session&&session.products)||{}}}
  function renderProductList(){var host=el('polaroidProductList'),items=products();host.innerHTML=items.length?items.map(function(p){var remaining=Number(p.stock)<0?'不限量':Math.max(0,Number(p.stock||0)-Number(p.sold||0))+' 份',thumb=p.imageUrl?'<img src="'+esc(p.imageUrl)+'" alt="">':'無圖片';return'<div class="polaroid-product-row"><div class="polaroid-product-thumb">'+thumb+'</div><div><strong>'+esc(p.name||'未命名商品')+'</strong><small>'+esc(p.category||'其他')+'・'+(p.processingMode==='delivery'?'完成後交付':'需要拍攝輪次')+'</small></div><div class="polaroid-product-meta">'+Number(p.price||0).toLocaleString('en-US')+' Gil</div><div class="polaroid-product-meta">剩餘 '+remaining+'</div><div class="polaroid-product-meta">'+(p.enabled===false?'已停賣':'販售中')+'</div><button class="btn ghost small" data-edit-product="'+esc(p.id)+'">編輯</button></div>'}).join(''):'<div class="queue-empty">尚未建立商品；可按「新增商品」開始。</div>'}
  function staffOptions(selected){return'<option value="">請選擇</option>'+Object.keys(roster).sort(function(a,b){return staffName(a).localeCompare(staffName(b),'zh-Hant')}).map(function(id){return'<option value="'+esc(id)+'" '+(id===selected?'selected':'')+'>'+esc(staffName(id))+'</option>'}).join('')}
  function fillProductStaffOptions(){var current=el('polaroidProductProvider').value;el('polaroidProductProvider').innerHTML=staffOptions(current);var selected=list(editingProduct&&editingProduct.revenueMaidIds);el('polaroidProductRevenueMaids').innerHTML=Object.keys(roster).sort(function(a,b){return staffName(a).localeCompare(staffName(b),'zh-Hant')}).map(function(id){return'<option value="'+esc(id)+'" '+(selected.indexOf(id)!==-1?'selected':'')+'>'+esc(staffName(id))+'</option>'}).join('')}
  function addExampleRow(value){value=value||{};var row=document.createElement('div');row.className='polaroid-example-row';row.dataset.id=value.id||('example_'+Date.now()+'_'+(++exampleSeed));row.dataset.url=value.url||'';row.dataset.storagePath=value.storagePath||'';row.innerHTML=(value.url?'<img src="'+esc(value.url)+'" alt="">':'<div class="polaroid-product-thumb">新範例</div>')+'<label>圖片<input data-example-file type="file" accept="image/jpeg,image/png,image/webp"><span><input data-example-public type="checkbox" '+(value.enabled===false?'':'checked')+'> 公開顯示</span></label><label>標題與說明<input data-example-title type="text" maxlength="80" value="'+esc(value.title||'')+'" placeholder="範例標題"><textarea data-example-description maxlength="300" rows="2" placeholder="範例說明">'+esc(value.description||'')+'</textarea></label><div class="polaroid-example-actions"><button class="btn ghost small" data-remove-example type="button">移除</button></div>';el('polaroidExampleEditor').appendChild(row)}
  function resetProductEditor(){editingProduct=null;el('polaroidProductEditorTitle').textContent='新增商品';el('polaroidProductId').value='';el('polaroidProductName').value='';el('polaroidProductCategory').value='';el('polaroidProductPrice').value='80000';el('polaroidProductStock').value='10';el('polaroidProductLimit').value='1';el('polaroidProductMode').value='round';el('polaroidProductRevenue').value='maid';el('polaroidProductDescription').value='';el('polaroidProductEnabled').checked=true;el('polaroidProductImage').value='';el('polaroidProductImagePreview').textContent='尚未上傳封面';el('polaroidExampleEditor').innerHTML='';el('polaroidDeleteProduct').hidden=true;fillProductStaffOptions()}
  function editProduct(id){var p=products().find(function(x){return x.id===id});if(!p)return;editingProduct=p;el('polaroidProductEditorTitle').textContent='編輯｜'+p.name;el('polaroidProductId').value=p.id;el('polaroidProductName').value=p.name||'';el('polaroidProductCategory').value=p.category||'';el('polaroidProductPrice').value=Number(p.price||0);el('polaroidProductStock').value=p.stock===undefined?-1:Number(p.stock);el('polaroidProductLimit').value=Number(p.perPersonLimit||1);el('polaroidProductMode').value=p.processingMode||'round';el('polaroidProductRevenue').value=p.revenueMode||'maid';el('polaroidProductDescription').value=p.description||'';el('polaroidProductEnabled').checked=p.enabled!==false;el('polaroidProductImage').value='';el('polaroidProductImagePreview').innerHTML=p.imageUrl?'<img src="'+esc(p.imageUrl)+'" alt="商品封面">':'尚未上傳封面';el('polaroidExampleEditor').innerHTML='';Object.values(p.examples||{}).sort(function(a,b){return Number(a.sortOrder||0)-Number(b.sortOrder||0)}).forEach(addExampleRow);el('polaroidDeleteProduct').hidden=false;fillProductStaffOptions();el('polaroidProductProvider').value=list(p.providerIds)[0]||'';Array.from(el('polaroidProductRevenueMaids').options).forEach(function(option){option.selected=list(p.revenueMaidIds).indexOf(option.value)!==-1});el('polaroidProductEditor').scrollIntoView({behavior:'smooth',block:'start'})}
  function upload(file,path){if(!file)return Promise.resolve(null);if(file.size>12*1024*1024)return Promise.reject(new Error('圖片不可超過 12 MB。'));return storage.ref(path).put(file,{contentType:file.type,cacheControl:'public,max-age=3600'}).then(function(s){return s.ref.getDownloadURL()}).then(function(url){return{url:url,storagePath:path}})}
  async function collectProduct(){var id=el('polaroidProductId').value||('product_'+Date.now()),base='polaroid-products/'+sessionId+'/'+id,image={url:editingProduct&&editingProduct.imageUrl||'',storagePath:editingProduct&&editingProduct.imageStoragePath||''},file=el('polaroidProductImage').files[0];if(file)image=await upload(file,base+'/cover-'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_'));var examples={};for(var i=0;i<el('polaroidExampleEditor').children.length;i++){var row=el('polaroidExampleEditor').children[i],exampleFile=row.querySelector('[data-example-file]').files[0],media={url:row.dataset.url||'',storagePath:row.dataset.storagePath||''};if(exampleFile)media=await upload(exampleFile,base+'/examples/'+Date.now()+'-'+i+'-'+exampleFile.name.replace(/[^a-zA-Z0-9._-]/g,'_'));if(media&&media.url)examples[row.dataset.id]={id:row.dataset.id,url:media.url,storagePath:media.storagePath,title:row.querySelector('[data-example-title]').value.trim(),description:row.querySelector('[data-example-description]').value.trim(),enabled:row.querySelector('[data-example-public]').checked,sortOrder:i*10}}var provider=el('polaroidProductProvider').value,revenueIds=Array.from(el('polaroidProductRevenueMaids').selectedOptions).map(function(o){return o.value});if(el('polaroidProductRevenue').value==='maid'&&!revenueIds.length&&provider)revenueIds=[provider];return{id:id,name:el('polaroidProductName').value.trim(),category:el('polaroidProductCategory').value.trim(),price:Number(el('polaroidProductPrice').value||0),stock:Number(el('polaroidProductStock').value),perPersonLimit:Number(el('polaroidProductLimit').value||1),processingMode:el('polaroidProductMode').value,providerIds:provider?[provider]:[],revenueMode:el('polaroidProductRevenue').value,revenueMaidIds:revenueIds,description:el('polaroidProductDescription').value.trim(),enabled:el('polaroidProductEnabled').checked,imageUrl:image&&image.url||'',imageStoragePath:image&&image.storagePath||'',examples:examples,sortOrder:editingProduct?Number(editingProduct.sortOrder||0):products().length*10}}
  function watch(){if(sessionRef)sessionRef.off();sessionId=operation.sessionId||'';if(!sessionId){session=null;render();return}sessionRef=db.ref('lephemere/polaroid/sessions/'+sessionId);sessionRef.on('value',function(s){session=s.val();el('polaroidSessionTitle').dataset.dirty='';render()})}
  firebase.auth().onAuthStateChanged(async function(user){if(!user)return;await checkRole(user);var snaps=await Promise.all([db.ref('lephemere/operationStatus').once('value'),db.ref('lephemere/staffRoster').once('value')]);operation=snaps[0].val()||{};roster=snaps[1].val()||{};watch()});db.ref('lephemere/operationStatus').on('value',function(s){operation=s.val()||{};watch()});db.ref('lephemere/staffRoster').on('value',function(s){roster=s.val()||{};render()});
  el('polaroidAdminTabs').addEventListener('click',function(e){var b=e.target.closest('[data-polaroid-pane]');if(!b||b.hasAttribute('data-manager-only')&&!isManager)return;document.querySelectorAll('[data-polaroid-pane]').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('[data-polaroid-panel]').forEach(function(x){x.hidden=x.dataset.polaroidPanel!==b.dataset.polaroidPane})});
  document.addEventListener('change',function(e){if(e.target.id==='globalStaffSelect')render();if(e.target.closest('[data-polaroid-panel="session"]'))el('polaroidSessionTitle').dataset.dirty='1'});
  el('polaroidAddRound').addEventListener('click',function(){addRoundRow();el('polaroidSessionTitle').dataset.dirty='1'});el('polaroidRoundEditor').addEventListener('click',function(e){if(e.target.matches('[data-remove-round]')){e.target.closest('.polaroid-round-row').remove();el('polaroidSessionTitle').dataset.dirty='1'}});
  el('polaroidStatusActions').addEventListener('click',function(e){var b=e.target.closest('[data-polaroid-status]'),id=staffId();if(!b||!id||!sessionId){alert('請先選擇操作女僕並建立本場設定。');return}setStatus({sessionId:sessionId,maidId:id,status:b.dataset.polaroidStatus}).catch(function(err){alert(err.message||'狀態更新失敗')})});
  el('polaroidTab').addEventListener('click',function(e){var b=e.target.closest('[data-photo-action]');if(!b)return;var id=staffId();if(!id&&!isManager){alert('請先選擇操作女僕。');return}b.disabled=true;updateTask({sessionId:sessionId,orderId:b.dataset.order,taskId:b.dataset.task,status:b.dataset.photoAction,maidId:id||b.dataset.maid}).catch(function(err){alert(err.message||'更新失敗');b.disabled=false})});
  el('polaroidSaveSession').addEventListener('click',function(){var status=el('polaroidSaveStatus'),data=collect();if(!data.sessionId){status.textContent='請先在「營業」開啟本次營業場次。';return}status.textContent='正在儲存…';this.disabled=true;saveSession(data).then(function(){status.textContent='本場設定已儲存。';el('polaroidSessionTitle').dataset.dirty=''}).catch(function(err){status.textContent=err.message||'儲存失敗'}).finally(function(){el('polaroidSaveSession').disabled=false})});
  el('polaroidNewProduct').addEventListener('click',resetProductEditor);el('polaroidProductList').addEventListener('click',function(e){var b=e.target.closest('[data-edit-product]');if(b)editProduct(b.dataset.editProduct)});el('polaroidAddExample').addEventListener('click',function(){addExampleRow()});el('polaroidExampleEditor').addEventListener('click',function(e){var b=e.target.closest('[data-remove-example]');if(b)b.closest('.polaroid-example-row').remove()});
  el('polaroidProductImage').addEventListener('change',function(){var file=this.files[0];if(file)el('polaroidProductImagePreview').innerHTML='<img src="'+URL.createObjectURL(file)+'" alt="封面預覽">'});
  el('polaroidSaveProduct').addEventListener('click',async function(){var status=el('polaroidProductStatus');if(!sessionId){status.textContent='請先建立本場設定。';return}if(!el('polaroidProductName').value.trim()){status.textContent='請填寫商品名稱。';return}if(!el('polaroidProductProvider').value){status.textContent='請選擇主要負責女僕。';return}this.disabled=true;status.textContent='正在上傳圖片並儲存…';try{var product=await collectProduct();await saveProduct({sessionId:sessionId,product:product});status.textContent='商品與範例已儲存。';editingProduct=product;el('polaroidProductId').value=product.id}catch(err){status.textContent=err.message||'儲存失敗'}finally{this.disabled=false}});
  el('polaroidDeleteProduct').addEventListener('click',function(){if(!editingProduct||!confirm('確定停止並移除這項商品嗎？既有訂單不會消失。'))return;var status=el('polaroidProductStatus');this.disabled=true;deleteProduct({sessionId:sessionId,productId:editingProduct.id}).then(function(){status.textContent='商品已停止販售；歷史訂單仍保留。';resetProductEditor()}).catch(function(err){status.textContent=err.message||'刪除失敗'}).finally(function(){el('polaroidDeleteProduct').disabled=false})});
  resetProductEditor();
})();
